openapi: 3.1.0
info:
  title: Users API
  version: 1.0.0
paths:
  /api/v1/users:
    get:
      summary: Buscar usuarios / Search users
      description: |
        Busca usuarios por nombre de usuario o nombre. Retorna hasta 10 resultados coincidentes.
        El término de búsqueda debe tener al menos 2 caracteres.

        *Requiere autenticación.*
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - name: query
          in: query
          required: true
          description: Término de búsqueda (username o name)
          schema:
            type: string
            minLength: 2
      responses:
        "200":
          description: Búsqueda exitosa / Successful search
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./partials/user.yml#/components/schemas/User"
        "401":
          $ref: "./partials/errors.yml#/components/responses/Unauthorized"
